site:
  title: Docs Site
  start_page: project-name::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    page-pagination: true
    hide-uri-scheme: ""
    kroki-server-url: 'https://kroki.schlichting.de'
    kroki-fetch-diagram: true
    # Allow URI read to retrieve SVG on compilation
    allow-uri-read: true
    # use SVG unless otherwise specified
    kroki-default-format: svg
    # Make SVG inline so that we can get interactive (can be overridden by schema with "opts=none")
    kroki-default-options: interactive
    sectnums: "@"
    xrefstyle: short@
    listing-caption: Code
    page-width-limit: none@